//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Rearrange.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REARRANGE_DIALOG            102
#define IDC_POINTER1                    104
#define IDR_MAINFRAME                   128
#define IDD_DIALOGSTOP                  130
#define IDC_POINTER2                    132
#define IDD_DIALOGSTOP2                 133
#define IDD_SEQGEN                      134
#define IDD_PROGRESS                    135
#define IDD_DIALOGSTARTUP               137
#define IDB_BITSTARTUP                  139
#define IDC_BUTLOADWAV                  1001
#define IDC_BUTNEWPROJ                  1004
#define IDC_BUTLOADPROJ                 1005
#define IDC_BUTSAVEASWAV                1006
#define IDC_BUTPLAYOFF                  1007
#define IDC_BUTGENSEQ                   1008
#define IDC_BUTDISPLAY                  1010
#define IDC_BUTCURROFF                  1011
#define IDC_BUTWNDSIZE                  1012
#define IDC_BUTPLAYSEQ                  1013
#define IDC_BUTRESDUR                   1014
#define IDC_EDITCURROFF                 1015
#define IDC_EDITWNDSIZE                 1016
#define IDC_EDITOFFFREQ                 1017
#define IDC_EDITSEQFREQ                 1018
#define IDC_EDITRES                     1019
#define IDC_EDITDUR                     1020
#define IDC_STATOFFFREQ                 1021
#define IDC_STATCURROFF                 1022
#define IDC_STATWNDSIZE                 1023
#define IDC_STATRESDUR                  1024
#define IDC_STATSEQFREQ                 1025
#define IDC_STATBACKG                   1027
#define IDC_BUTSAVEPROJ                 1028
#define IDC_STATBACKG2                  1029
#define IDC_BUTNEWSEQ                   1030
#define IDC_SCROLIRREG                  1035
#define IDC_SCROLDISARR                 1036
#define IDC_SCROLDENS                   1037
#define IDC_STATDISARR                  1038
#define IDC_STATIRREG                   1039
#define IDC_STATDENS                    1040
#define IDC_STATRES                     1041
#define IDC_STATDUR                     1042
#define IDC_STATOFF                     1043
#define IDC_EDITDUR2                    1044
#define IDC_EDITRES2                    1045
#define IDC_EDITOFF2                    1046
#define IDC_SPINOFFFREQ                 1049
#define IDC_SPINSEQFREQ                 1050
#define IDC_STATPROG                    1050
#define IDC_CHEKSMOO                    1053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
